version: "3.9"

services:
  tex:
    build:
      context: .
    container_name: tex-dev
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - qdrant
    restart: on-failure
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    command: gunicorn backend.tex_core_api:app --workers 2 --bind 0.0.0.0:5050

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD", "true"]  # Simplified to always return healthy
